version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  api:
    container_name: api
    image: utfprapps-api
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8081:8081"
      - "5005:5005"
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres: