services:

  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5433"
    networks:
      - postgresql
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address :9001
    networks:
      - postgresql
  api:
    container_name: api
    working_dir: /home/java/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - postgresql
    depends_on:
      - postgresql
    restart: always

networks:
  postgresql:
    driver: bridge

volumes:
  db:



