version: '3.1'
services:

  postgresql:
    image: postgres
    ports:
      - "5423:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: apioficina

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address :9001

  api:
    container_name: apioficina
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql


