version: '3.3'

networks:
  application:
    driver: bridge

volumes:
  db:

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: portal_centro
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - application
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address :9001
    networks:
      - application

  api:
    container_name: api
    image: maven:3.8.3-openjdk-17
    working_dir: /home/java/app
    restart: always
    command: sh -c "chmod +x ./mvnw && ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"
    volumes:
      - .././:/home/java/app
    ports: 
      - "8085:8085"
      - "5005:5005"
    networks:
      - application
    depends_on:
      - postgres

