version: '3.3'

networks:
  api:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana8'
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/:/etc/grafana/
    environment:
      - GF_LOG_MODE=console file
      - GF_LOG_LEVEL=trace
    env_file:
      - ./monitoring/grafana/config.monitoring
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
      - '9300:9300'
  logstash:
    image: logstash:8.6.2
    container_name: 'logstash'
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
    volumes:
      - ./monitoring/logstash/pipe/:/usr/share/logstash/load
      - ./monitoring/logstash/conf/:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:8.6.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://172.17.0.1:9200/"]'
    depends_on:
      - elasticsearch
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:trunk-ubuntu
    restart: always
    environment:
      DB_SERVER_HOST: 172.17.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portal_centro
    volumes:
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    ports:
      - "10050:10050"
      - "10051:10051"
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:trunk-ubuntu
    restart: always
    environment:
      DB_SERVER_HOST: 172.17.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portal_centro
      PHP_TZ: "America/Sao_Paulo"
    depends_on:
      - zabbix-server
    ports:
      - "80:8080"
      - "443:8443"
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10053:10053'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.17.0.1